wandb_version: 1

env_id:
  desc: null
  value: Skip-v0
learning_rate:
  desc: null
  value: 0.0001
initial_epsilon:
  desc: null
  value: 1.0
final_epsilon:
  desc: null
  value: 0.01
'epsilon_decay_steps:':
  desc: null
  value: 20000
gamma:
  desc: null
  value: 0.99
learning_starts:
  desc: null
  value: 100
seed:
  desc: null
  value: 984
algo:
  desc: null
  value: RCPO
_wandb:
  desc: null
  value:
    code_path: code/policy_constraint.py
    python_version: 3.10.0
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722421675
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 7
      - 13
      - 16
      - 23
      - 35
      4: 3.10.0
      5: 0.17.5
      8:
      - 3
      - 5
      13: windows-amd64
